apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.deployment.component }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  selector:
    matchLabels:
      project: {{ .Values.deployment.labels.project }}
      component: {{ .Values.deployment.component }}
      tier: {{ .Values.deployment.labels.tier }} # has to match .spec.template.metadata.labels
  serviceName: "{{ .Values.deployment.component }}-headless" # this should be head less service name
  replicas: {{ .Values.deployment.replicas }} # by default is 1
  template:
    metadata:
      labels:
        project: {{ .Values.deployment.labels.project }}
        component: {{ .Values.deployment.component }}
        tier: {{ .Values.deployment.labels.tier }} # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: {{ .Values.deployment.component }}
        image: "{{ .Values.deployment.imageRepo}}:{{ .Values.deployment.imageTag }}"
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
        volumeMounts:
        - name: {{ .Values.deployment.component }}
          mountPath: /data/db
  # This is PVC
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.deployment.component }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi